name: Render Quarto to docs (main)

on:
  push:
    branches: [main]     # rulează la orice commit pe main
  workflow_dispatch:      # permite rularea manuală din Actions

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render site to docs
        run: quarto render
      - name: Commit rendered docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Auto-render docs [skip ci]" || echo "No changes to commit"
          git push
